name: BR-MineHunt
version: '${project.version}'
main: com.ghostchu.plugins.brminehunt.BR_MineHunt
api-version: '1.20'
depend:
  - Chunky
  - ProtocolLib
  - ReplaySystem
commands:
  minehunt:
    usage: /minehunt
    description: /minehunt