name: BR-MineHunt
version: '1.0-SNAPSHOT'
main: com.ghostchu.plugins.brminehunt.BR_MineHunt
api-version: '1.20'
depend:
  - Chunky
commands:
  minehunt:
    usage: /minehunt
    description: /minehunt